from __future__ import annotations

import argparse
import json
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Any


SEVERITY_ORDER = {
    "critical": 0,
    "high": 1,
    "medium": 2,
    "low": 3,
    "informational": 4,
}


@dataclass(frozen=True)
class EvidencePaths:
    scan: Path
    auth: Path
    findings: Path


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate a Markdown cybersecurity assessment report."
    )
    parser.add_argument("--scan", type=Path, required=True, help="Port scanner JSON path.")
    parser.add_argument(
        "--auth", type=Path, required=True, help="Authentication alert JSON path."
    )
    parser.add_argument(
        "--findings",
        type=Path,
        default=Path("report_generator/findings.json"),
        help="Curated web findings JSON path. Default: report_generator/findings.json.",
    )
    parser.add_argument("--output", type=Path, required=True, help="Markdown output path.")
    return parser.parse_args()


def load_json(path: Path) -> Any:
    return json.loads(path.read_text(encoding="utf-8"))


def load_findings(path: Path) -> list[dict[str, Any]]:
    findings = load_json(path)
    if not isinstance(findings, list):
        raise ValueError("findings file must contain a list")

    required_fields = {
        "id",
        "title",
        "severity",
        "source_module",
        "category",
        "evidence",
        "impact",
        "risk_summary",
        "remediation",
        "control_summary",
        "verification",
        "references",
    }
    for finding in findings:
        if not isinstance(finding, dict):
            raise ValueError("each finding must be an object")
        missing = required_fields - set(finding)
        if missing:
            missing_fields = ", ".join(sorted(missing))
            raise ValueError(f"finding {finding.get('id', '<unknown>')} missing: {missing_fields}")

    return findings


def severity_sort_key(finding: dict[str, Any]) -> tuple[int, str]:
    severity = str(finding.get("severity", "")).lower()
    return SEVERITY_ORDER.get(severity, len(SEVERITY_ORDER)), str(finding.get("id", ""))


def escape_table_value(value: object) -> str:
    return str(value).replace("|", "\\|").replace("\n", " ")


def build_auth_finding(
    finding_id: str,
    title: str,
    severity: str,
    evidence: str,
    impact: str,
    risk_summary: str,
    remediation: str,
    control_summary: str,
    references: list[str],
) -> dict[str, Any]:
    return {
        "id": finding_id,
        "title": title,
        "severity": severity,
        "source_module": "log_analyzer",
        "category": "Authentication Monitoring",
        "evidence": evidence,
        "impact": impact,
        "risk_summary": risk_summary,
        "remediation": remediation,
        "control_summary": control_summary,
        "verification": "Generated by the authentication log analyzer from the supplied JSON alert report.",
        "references": references,
    }


def auth_alerts_to_findings(auth_report: dict[str, Any]) -> list[dict[str, Any]]:
    findings = []
    suspicious_username_alerts = []
    next_id = 1

    for alert in auth_report.get("alerts", []):
        rule = alert.get("rule", "unknown_rule")
        if rule == "suspicious_username":
            suspicious_username_alerts.append(alert)
            continue

        severity = alert.get("severity", "informational")
        ip = alert.get("ip", "unknown")
        username = alert.get("username")
        count = alert.get("count")
        message = alert.get("message", "Authentication alert generated.")

        if rule == "success_after_failures":
            title = "Successful Login After Repeated Failures"
            impact = (
                "A successful login after repeated failures may indicate that password "
                "guessing eventually found valid credentials."
            )
            risk_summary = "Possible credential compromise"
            remediation = (
                "Review account activity, reset credentials if compromise is suspected, "
                "revoke active sessions, and consider rate limiting or multi-factor authentication."
            )
            control_summary = "Account review, credential reset, MFA, and rate limiting"
            references = [
                "MITRE ATT&CK T1110 - Brute Force",
                "MITRE ATT&CK T1110.001 - Password Guessing",
            ]
        elif rule == "repeated_failed_logins":
            title = "Repeated Failed Login Attempts"
            impact = (
                "Repeated authentication failures from the same IP may indicate brute-force "
                "or password-guessing activity."
            )
            risk_summary = "Possible brute-force activity"
            remediation = (
                "Apply rate limiting, monitor repeated failures, and investigate whether the "
                "source IP is associated with other suspicious activity."
            )
            control_summary = "Rate limiting and repeated-failure monitoring"
            references = ["MITRE ATT&CK T1110 - Brute Force"]
        else:
            title = "Suspicious Username Attempt"
            impact = (
                "Attempts against commonly targeted usernames may indicate automated scanning "
                "or credential-guessing behavior."
            )
            risk_summary = "Possible account discovery or credential guessing"
            remediation = (
                "Monitor repeated attempts against privileged or default usernames and remove "
                "unused default accounts."
            )
            control_summary = "Default account review and username-attempt monitoring"
            references = ["Detection triage rule"]

        evidence_parts = [message, f"Source IP: {ip}"]
        if username:
            evidence_parts.append(f"Username: {username}")
        if count is not None:
            evidence_parts.append(f"Count: {count}")

        findings.append(
            build_auth_finding(
                finding_id=f"A-{next_id:03d}",
                title=title,
                severity=severity,
                evidence=" ".join(evidence_parts),
                impact=impact,
                risk_summary=risk_summary,
                remediation=remediation,
                control_summary=control_summary,
                references=references,
            )
        )
        next_id += 1

    if suspicious_username_alerts:
        evidence_items = []
        for alert in suspicious_username_alerts:
            ip = alert.get("ip", "unknown")
            username = alert.get("username", "unknown")
            evidence_items.append(f"{ip} attempted username '{username}'")

        findings.append(
            build_auth_finding(
                finding_id=f"A-{next_id:03d}",
                title="Suspicious Username Attempts",
                severity="medium",
                evidence="; ".join(evidence_items) + ".",
                impact=(
                    "Attempts against commonly targeted usernames may indicate automated "
                    "scanning or credential-guessing behavior."
                ),
                risk_summary="Possible account discovery or credential guessing",
                remediation=(
                    "Monitor repeated attempts against privileged or default usernames and "
                    "remove unused default accounts."
                ),
                control_summary="Default account review and username-attempt monitoring",
                references=["Detection triage rule"],
            )
        )

    return findings


def render_network_summary(scan_report: dict[str, Any]) -> list[str]:
    target = scan_report.get("target", "unknown")
    ip_address = scan_report.get("ip_address", "unknown")
    port_range = scan_report.get("port_range", {})
    open_ports = scan_report.get("open_ports", [])
    start_port = port_range.get("start", "unknown")
    end_port = port_range.get("end", "unknown")

    lines = [
        "## Network Reconnaissance Summary",
        "",
        f"- Target: `{target}`",
        f"- Resolved IP: `{ip_address}`",
        f"- Port range: `{start_port}-{end_port}`",
        f"- Open ports found: {len(open_ports)}",
        "",
    ]

    if open_ports:
        lines.extend(["| Port | Service | Status |", "| --- | --- | --- |"])
        for port in open_ports:
            lines.append(
                "| "
                f"{escape_table_value(port.get('port', 'unknown'))} | "
                f"{escape_table_value(port.get('service', 'unknown'))} | "
                f"{escape_table_value(port.get('status', 'unknown'))} |"
            )
    else:
        lines.append("No open ports were found in the supplied scan output.")

    return lines


def render_findings_summary(findings: list[dict[str, Any]]) -> list[str]:
    lines = [
        "## Findings Summary",
        "",
        "| ID | Finding | Severity | Source | References |",
        "| --- | --- | --- | --- | --- |",
    ]

    for finding in sorted(findings, key=severity_sort_key):
        references = ", ".join(finding.get("references", []))
        lines.append(
            "| "
            f"{escape_table_value(finding['id'])} | "
            f"{escape_table_value(finding['title'])} | "
            f"{escape_table_value(str(finding['severity']).title())} | "
            f"{escape_table_value(finding['source_module'])} | "
            f"{escape_table_value(references)} |"
        )

    return lines


def render_detailed_findings(findings: list[dict[str, Any]]) -> list[str]:
    lines = ["## Detailed Findings", ""]
    for finding in sorted(findings, key=severity_sort_key):
        lines.extend(
            [
                f"### {finding['id']}: {finding['title']}",
                "",
                f"**Severity:** {str(finding['severity']).title()}",
                "",
                f"**Category:** {finding['category']}",
                "",
                "**Evidence:**",
                "",
                str(finding["evidence"]),
                "",
                "**Impact:**",
                "",
                str(finding["impact"]),
                "",
                "**Remediation:**",
                "",
                str(finding["remediation"]),
                "",
                "**Verification:**",
                "",
                str(finding["verification"]),
                "",
                "**References:**",
                "",
            ]
        )
        lines.extend(f"- {reference}" for reference in finding.get("references", []))
        lines.append("")

    return lines


def render_control_matrix(findings: list[dict[str, Any]]) -> list[str]:
    lines = [
        "## Security Control Matrix",
        "",
        "| Finding | Risk | Control | Verification |",
        "| --- | --- | --- | --- |",
    ]
    for finding in sorted(findings, key=severity_sort_key):
        lines.append(
            "| "
            f"{escape_table_value(finding['id'])} | "
            f"{escape_table_value(finding['risk_summary'])} | "
            f"{escape_table_value(finding['control_summary'])} | "
            f"{escape_table_value(finding['verification'])} |"
        )
    return lines


def render_evidence_sources(
    paths: EvidencePaths, auth_report: dict[str, Any], generated_at: str
) -> list[str]:
    detection_window = auth_report.get("detection_window_minutes", "unknown")
    return [
        "## Evidence Sources",
        "",
        f"- Scanner input: `{paths.scan}`",
        f"- Log analysis input: `{paths.auth}`",
        f"- Curated web findings: `{paths.findings}`",
        f"- Generated: `{generated_at}`",
        f"- Detection window: `{detection_window}` minutes",
        "",
        "The curated web findings are structured demonstration findings. The generator does not automatically discover web vulnerabilities.",
    ]


def render_report(
    scan_report: dict[str, Any],
    auth_report: dict[str, Any],
    curated_findings: list[dict[str, Any]],
    paths: EvidencePaths,
    generated_at: str | None = None,
) -> str:
    generated_at = generated_at or datetime.now(timezone.utc).replace(microsecond=0).isoformat()
    auth_findings = auth_alerts_to_findings(auth_report)
    all_findings = curated_findings + auth_findings

    lines = [
        "# Automated Cybersecurity Assessment Report",
        "",
        "## Executive Summary",
        "",
        (
            "This report was generated from structured evidence produced by the lab modules: "
            "port scanner output, authentication log alerts, and curated web application findings."
        ),
        "",
        f"- Total findings: {len(all_findings)}",
        f"- Web findings: {len(curated_findings)}",
        f"- Authentication findings: {len(auth_findings)}",
        f"- Open ports found: {len(scan_report.get('open_ports', []))}",
        "",
        "## Scope",
        "",
        "This generated report covers local and synthetic lab evidence only. It is intended for reproducible security assessment practice, not for unauthorized testing.",
        "",
        "## Methodology",
        "",
        "1. Review scanner JSON output for exposed services.",
        "2. Include curated web application findings from the controlled vulnerable app demos.",
        "3. Include authentication alerts generated by the log analyzer.",
        "4. Produce a Markdown assessment report with evidence, impact, remediation, and verification guidance.",
        "",
    ]
    lines.extend(render_network_summary(scan_report))
    lines.extend([""])
    lines.extend(render_findings_summary(all_findings))
    lines.extend([""])
    lines.extend(render_detailed_findings(all_findings))
    lines.extend(render_control_matrix(all_findings))
    lines.extend([""])
    lines.extend(render_evidence_sources(paths, auth_report, generated_at))
    lines.extend(
        [
            "",
            "## Limitations",
            "",
            "- The web findings are curated demo findings, not automatically discovered vulnerabilities.",
            "- The authentication log data is synthetic.",
            "- The scanner output identifies open ports but does not perform service fingerprinting or exploitation.",
            "",
            "## Conclusion",
            "",
            "The generated report connects reconnaissance output, web security findings, detection alerts, and remediation guidance into a reproducible assessment workflow.",
        ]
    )

    return "\n".join(lines) + "\n"


def generate_report(scan_path: Path, auth_path: Path, findings_path: Path, output_path: Path) -> None:
    scan_report = load_json(scan_path)
    auth_report = load_json(auth_path)
    findings = load_findings(findings_path)
    paths = EvidencePaths(scan=scan_path, auth=auth_path, findings=findings_path)
    report = render_report(scan_report, auth_report, findings, paths)

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(report, encoding="utf-8")


def main() -> int:
    args = parse_args()
    try:
        generate_report(args.scan, args.auth, args.findings, args.output)
    except (OSError, ValueError, json.JSONDecodeError) as exc:
        print(f"Error: {exc}")
        return 1

    print(f"Assessment report saved to {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
